#!/bin/sh
lb config noauto \
     -b iso \
     --bootappend-live "boot=live components quiet splash locales=en_US.UTF-8 keyboard-layouts=es,us persistence" \
     --archive-areas "main contrib non-free non-free-firmware" \
     --parent-archive-areas "main contrib non-free non-free-firmware" \
     --distribution stable \
     --distribution-chroot stable \
     --distribution-binary stable \
     --debian-installer-distribution stable \
     --parent-distribution stable \
     --parent-distribution-chroot stable \
     --parent-distribution-binary stable \
     --parent-debian-installer-distribution stable \
     --chroot-filesystem squashfs \
     --image-name debian-live \
     --initsystem systemd \
     --system live \
     "${@}"
